rootProject.name = "Tesera"
include(":app",":core")
include(":data")
include(":domain")
include(":feature:login")
include(":feature:splash")
include(":feature:dashboard")
include(":feature:home")
include(":feature:search")
include(":feature:profile")
include(":designsystem")
